### ISSUE TITLE
Issue with Spring Boot 2.3.4 - Upgrade to Snake YAML 1.26

### ISSUE THREAD

**Issue by josephearl** [azagniotov/stubby4j#106]
When upgrading the Spring Boot version from 2.3.3 to 2.3.4, the Spring Boot tests fail to start with:

```
java.lang.NoSuchMethodError: org.yaml.snakeyaml.LoaderOptions.setMaxAliasesForCollections(I)V
        at org.springframework.boot.env.OriginTrackedYamlLoader.createYaml(OriginTrackedYamlLoader.java:67)
```

I have created a minimal reproducible example with instructions at https://github.com/josephearl/spring-boot-stubby4j-example.

**Comment by azagniotov** [comment]
Hi @josephearl , perhaps it is time to upgrade SnakeYAML. It looks like there are two versions on the classpath where on of the versions may be outdated...

**Comment by josephearl** [comment]
I'm not really clear on why it happens given I am using Spring's Dependency Management, which sets snakeyaml 1.26 as a managed dependency, so there should be only 1 version on the classpath...

**Comment by josephearl** [comment]
Oh yes, on further inspection of the README it says the stubby4j is a fat jar, so my mistake is not using the `no-dependencies` classifier. After testing with that it works fine.

It might be worth considering using different artifacts rather than using different classifiers - mostly for visibility - tools like Maven central don't surface available classifiers (unless I'm looking in the wrong place) https://search.maven.org/artifact/io.github.azagniotov/stubby4j/6.0.2/jar.

Will submit a PR for the dependency upgrade regardless.
